---

# Install scripts requiring a GitHub OAuth token
- name: Install requests Python library
  pip: name=requests state=present

- fail: OAuth token not defined
  when: github_oauth_token is not defined

- name: Install Python GitHub PR auth script
  template: src="github_pr_auth.py.j2" dest="/usr/local/bin/github_pr_auth.py"
            owner=root group=root
            mode=755

- name: Install Python GitHub post status script
  template: src="github_post_status.py.j2" dest="/usr/local/bin/github_post_status.py"
            owner=root group=root
            mode=755

# Create a virtualenv for edx-platform by installing the requirements
# and packaging the virtualenv.
# A shallow clone is created off of master. The depth setting
# refers to the --depth-setting of git clone. A value of 1
# will truncate all history prior to the last revision.
- name: Create shallow clone of edx-platform
  git: >
    repo=https://github.com/edx/edx-platform.git
    dest={{ jenkins_home }}/shallow-clone
    version=master
    depth=1
  sudo_user: "{{ jenkins_user }}"

# The s3 upload functionality we want has not yet been merged to
# the pip-accel repo. Get it from GitHub instead of pypi for now.
- name: Install pip-accel for caching python requirements
  pip: >
    name='git+https://github.com/jzoldak/pip-accel.git@830fb4b3f169774d156e6e7fbba4f2ae421b0ec6#egg=pip-accel'
    virtualenv={{ jenkins_home }}/edx-venv
    virtualenv_command=virtualenv-2.7
  sudo_user: "{{ jenkins_user }}"

# pip-accel only makes the s3 functionality available
# if you have installed boto yourself.
- name: Install boto for caching python requirements
  pip: >
    name='boto' version='2.34.0'
    virtualenv={{ jenkins_home }}/edx-venv
    virtualenv_command=virtualenv-2.7
  sudo_user: "{{ jenkins_user }}"

- name: Install edx-platform requirements using pip-accel
  pip: >
    requirements={{ jenkins_home }}/shallow-clone/requirements/edx/{{ item }}
    virtualenv={{ jenkins_home }}/edx-venv
    virtualenv_command=virtualenv-2.7
    executable=pip-accel

  with_items:
    - pre.txt
    - github.txt
    - base.txt
    - post.txt
  sudo_user: "{{ jenkins_user }}"

# There is a bug in pip-accel that causes an error when used to install paver.
# Install using the native pip instead.
- name: Install paver requirements using pip
  pip: >
    requirements={{ jenkins_home }}/shallow-clone/requirements/edx/paver.txt
    extra_args="--exists-action w --download-cache ~/.pip/download-cache"
    virtualenv={{ jenkins_home }}/edx-venv
    virtualenv_command=virtualenv-2.7
    executable=pip

  sudo_user: "{{ jenkins_user }}"

# Archive the current state of the virtualenv
# as a starting point for new builds.
# The edx-venv directory is deleted and then recreated
# cleanly from the archive by the jenkins build scripts.
- name: Create a clean virtualenv archive
  command: >
    tar -cpzf edx-venv_clean.tar.gz edx-venv
    chdir={{ jenkins_home }}
  sudo_user: "{{ jenkins_user }}"

# Remove the shallow-clone directory now that we archive
# done with it
- name: Remove shallow-clone
  file: path={{ jenkins_home }}/shallow-clone state=absent
